### ISSUE TITLE
To time showing and no timer

### ISSUE THREAD

**Issue by n00bster-za** [wernerhp/ha_integration_load_shedding#3]
I have configured everything and the card is showing as per screenshot just without the 15 min warning. 

But my "Next Start" is not showing and "Time Until" not showing

 Can anyone help.

**Comment by Arnoldsly99ZA** [comment]
Same here. State shows stage, but no attribute for loadshedding time:

```
attribution: Data provided by Eskom
icon: mdi:calendar
friendly_name: Load Shedding AREA
```

**Comment by n00bster-za** [comment]
Yes. So I am not a direct Eskom client. So I just added a suburb that is with Eskom direct and have the correct schedule as my own. 

Now my issue is to clean it up the "Next Time" just want Date and time not the time zone as well. 

Also my "Time Until" showed 1 day and 20 min but my load shedding was only in 20 min. It is somehow adding a day

**Comment by wernerhp** [comment]
I only integrated Eskom direct from loadshedding.eskom.co.za since that's what i needed.  This project and [the library](https://gitlab.com/wernerhp/load-shedding) are open source so anyone can contribute other municipalities.  
Unsupported municipalities will only show the Stage without the schedule data.  If the schedule data is available it will show in the sensor attributes.

![image](https://user-images.githubusercontent.com/2578772/168235174-39079eac-0330-4f0e-8599-ca98f7b21588.png)

So without the schedule data the Next Start and Time Until is not available.

Kudos on the workaround @n00bster-za!
